name: Build Wheels (macOS)

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build_wheels_macos:
    name: Build wheels on macOS (arm64, x86_64, universal2)
    # Use macOS-14 (ARM64) runner which can test both ARM64 and x86_64 via Rosetta 2
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get libpostal submodule commit hash
        id: get_submodule_hash
        shell: bash
        run: |
          HASH=$(git submodule status vendor/libpostal | awk '{ sub(/^[+-]?/, ""); print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install cibuildwheel
        run: python -m pip install --upgrade pip cibuildwheel

      # Ensure the base cache directory exists
      - name: Create cache directory structure
        run: mkdir -p build/libpostal_install_cache

      # --- Restore a single shared cache for all architectures ---
      - name: Cache libpostal libraries
        uses: actions/cache@v4
        id: cache-macos
        with:
          path: build/libpostal_install_cache
          key: macos-all-libpostal-cache-v2-${{ steps.get_submodule_hash.outputs.hash }}
          restore-keys: |
            macos-all-libpostal-cache-v2-

      # --- arm64 ---
      - name: Build arm64 wheels
        run: |
          export CIBW_ARCHS=arm64
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: arm64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: |
            python -c "
            import os
            import sys

            print('Testing postal import...')
            import postal
            print(f'postal imported successfully. __file__={postal.__file__}')

            print('\\nTesting postal parser functionality...')
            from postal.parser import parse_address
            parsed = parse_address('781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA')
            print(f'Address parsed: {parsed}')
            
            # Basic verification of parsing results
            expected_components = {
                'house_number': '781',
                'road': 'franklin ave',
                'suburb': 'crown heights',
                'city_district': 'brooklyn',
                'city': 'nyc',
                'state': 'ny'
            }
            
            match_count = 0
            for component, label in parsed:
                if label in expected_components and expected_components[label].lower() == component.lower():
                    match_count += 1
                    
            if match_count >= 4:  # At least 4 key components should match
                print('✓ Parser test passed')
            else:
                print('✗ Parser test failed')
                sys.exit(1)
                
            print('\\nTesting postal expansion functionality...')
            from postal.expand import expand_address
            expansions = expand_address('123 Main St Apt 4')
            print(f'Expansions: {expansions[:3]}...')
            
            # Basic verification of expansion results
            if len(expansions) > 0 and '123 main street apartment 4' in expansions:
                print('✓ Expansion test passed')
            else:
                print('✗ Expansion test failed')
                sys.exit(1)
                
            print('\\nAll tests passed successfully!')
            "

      # --- x86_64 ---
      - name: Build x86_64 wheels
        run: |
          export CIBW_ARCHS=x86_64
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: x86_64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: |
            python -c "
            import os
            import sys

            print('Testing postal import...')
            import postal
            print(f'postal imported successfully. __file__={postal.__file__}')

            print('\\nTesting postal parser functionality...')
            from postal.parser import parse_address
            parsed = parse_address('781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA')
            print(f'Address parsed: {parsed}')
            
            # Basic verification of parsing results
            expected_components = {
                'house_number': '781',
                'road': 'franklin ave',
                'suburb': 'crown heights',
                'city_district': 'brooklyn',
                'city': 'nyc',
                'state': 'ny'
            }
            
            match_count = 0
            for component, label in parsed:
                if label in expected_components and expected_components[label].lower() == component.lower():
                    match_count += 1
                    
            if match_count >= 4:  # At least 4 key components should match
                print('✓ Parser test passed')
            else:
                print('✗ Parser test failed')
                sys.exit(1)
                
            print('\\nTesting postal expansion functionality...')
            from postal.expand import expand_address
            expansions = expand_address('123 Main St Apt 4')
            print(f'Expansions: {expansions[:3]}...')
            
            # Basic verification of expansion results
            if len(expansions) > 0 and '123 main street apartment 4' in expansions:
                print('✓ Expansion test passed')
            else:
                print('✗ Expansion test failed')
                sys.exit(1)
                
            print('\\nAll tests passed successfully!')
            "

      # --- universal2 ---
      - name: Build universal2 wheels
        run: |
          export CIBW_ARCHS=universal2
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: universal2
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: |
            python -c "
            import os
            import sys

            print('Testing postal import...')
            import postal
            print(f'postal imported successfully. __file__={postal.__file__}')

            print('\\nTesting postal parser functionality...')
            from postal.parser import parse_address
            parsed = parse_address('781 Franklin Ave Crown Heights Brooklyn NYC NY 11216 USA')
            print(f'Address parsed: {parsed}')
            
            # Basic verification of parsing results
            expected_components = {
                'house_number': '781',
                'road': 'franklin ave',
                'suburb': 'crown heights',
                'city_district': 'brooklyn',
                'city': 'nyc',
                'state': 'ny'
            }
            
            match_count = 0
            for component, label in parsed:
                if label in expected_components and expected_components[label].lower() == component.lower():
                    match_count += 1
                    
            if match_count >= 4:  # At least 4 key components should match
                print('✓ Parser test passed')
            else:
                print('✗ Parser test failed')
                sys.exit(1)
                
            print('\\nTesting postal expansion functionality...')
            from postal.expand import expand_address
            expansions = expand_address('123 Main St Apt 4')
            print(f'Expansions: {expansions[:3]}...')
            
            # Basic verification of expansion results
            if len(expansions) > 0 and '123 main street apartment 4' in expansions:
                print('✓ Expansion test passed')
            else:
                print('✗ Expansion test failed')
                sys.exit(1)
                
            print('\\nAll tests passed successfully!')
            "

      # --- Save the single shared cache ---
      - name: Save cache
        uses: actions/cache@v4
        if: always()
        with:
          path: build/libpostal_install_cache
          key: macos-all-libpostal-cache-v2-${{ steps.get_submodule_hash.outputs.hash }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-all
          path: ./wheelhouse/*.whl
