name: Build Wheels (macOS)

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: "0 12 1 * *"

jobs:
  build_wheels_macos:
    name: Build wheels on macOS (arm64, x86_64, universal2)
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get libpostal submodule commit hash
        id: get_submodule_hash
        shell: bash
        run: |
          HASH=$(git submodule status vendor/libpostal | awk '{ sub(/^[+-]?/, ""); print $1 }')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      # --- arm64 ---
      - name: Restore arm64 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-arm64-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}
          restore-keys: |
            macos-arm64-libpostal-cache-
      - name: Build arm64 wheels
        run: |
          export CIBW_ARCHS=arm64
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: arm64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: "python -c \"import os; print('Testing postal import...'); import postal; print(f'postal imported successfully. __file__={postal.__file__}')\""
      - name: Save arm64 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-arm64-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}

      # --- x86_64 ---
      - name: Restore x86_64 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-x86_64-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}
          restore-keys: |
            macos-x86_64-libpostal-cache-
      - name: Build x86_64 wheels
        run: |
          export CIBW_ARCHS=x86_64
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: x86_64
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: "python -c \"import os; print('Testing postal import...'); import postal; print(f'postal imported successfully. __file__={postal.__file__}')\""
      - name: Save x86_64 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-x86_64-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}

      # --- universal2 ---
      - name: Restore universal2 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-universal2-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}
          restore-keys: |
            macos-universal2-libpostal-cache-
      - name: Build universal2 wheels
        run: |
          export CIBW_ARCHS=universal2
          cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp311-* cp312-*"
          CIBW_BEFORE_BUILD_MACOS: "brew install autoconf automake libtool pkg-config curl"
          CIBW_ARCHS: universal2
          CIBW_SKIP: "pp* *-musllinux_* cp37-win*"
          CIBW_BUILD_VERBOSITY: "1"
          CIBW_TEST_COMMAND: "python -c \"import os; print('Testing postal import...'); import postal; print(f'postal imported successfully. __file__={postal.__file__}')\""
      - name: Save universal2 cache
        uses: actions/cache@v4
        with:
          path: build/libpostal_install_cache
          key: macos-universal2-libpostal-cache-${{ steps.get_submodule_hash.outputs.hash }}

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-macos-all
          path: ./wheelhouse/*.whl
